### ISSUE TITLE
Error in right or left click

### ISSUE THREAD

**Issue by Paul75** [bfwg/ngx-drag-scroll#187] opened 2018-11-17 13:51 UTC
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Error when click left

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co
See : 
https://stackblitz.com/edit/angular-vlkkw2

* **What is the expected behavior?**
It take erro when I want to do a button out of th component. In another component when Include the component slider into constructor and call function clickLeft or right it take error : ERROR

Error: this.ds is undefined; can't access its "moveRight" property

 ==> see sample

* **Please tell us about your environment:**
  
  - Version: 2.0.2
  - Browser: all

Thanks

**Comment by bfwg** [comment] 2019-01-25 18:13
Duplicate of #186

**Closed by bfwg** 2019-01-25 18:13 UTC
