### ISSUE TITLE
method moveRight doesn't work Or RTL support issues

### ISSUE THREAD

**Issue by MortezaT** [bfwg/ngx-drag-scroll#146] opened 2018-06-19 10:22 UTC
* **I'm submitting a ...**
  - [x] bug report
* **What is the current behavior?**
I got one issue report and one question to ask.
1- I think `currIndex` has been set out of array boundary by mistake In function `CurrentChildWith` (line 274) and it should be set to `length - 1` - just like the if statement's condition -. this stops move right 
2- I think there are lots of problems with `RTL` support since `reachesRightBound` is emits false in the very beginning and `moveLeft` works even after reaching left bound but it's not the same on right bound.

**Comment by bfwg** [comment] 2018-06-22 17:54
Hi @MortezaT , sorry for the delayed response. Can you give me some reproducing steps and a use case so I can take a closer look? Thanks!

**Comment by MortezaT** [comment] 2018-06-25 07:43
Hi @bfwg, Thanks for the response.
Currently I'm pretty busy with some other stuff, but I'll do it ASAP.

**Comment by bfwg** [comment] 2018-06-25 16:58
No problem, take your time.

**Comment by MortezaT** [comment] 2018-07-07 10:42
[here](https://alounak.com/advert/5af8232234875559bfb1a982) you can see my implementation. I hope this helps with the problem.

**Comment by bfwg** [comment] 2018-07-11 22:15
Hi @MortezaT , 2.0.0-beta.2 is out, let me know it made your implementation issue worst or better. Thanks!

**Comment by MortezaT** [comment] 2018-07-14 12:29
Neither beta.2 nor beta.3 worked at all.
they both come up with error which suggests that it hasn't been recognized by angular. Here is the error:

     Can't bind to 'scrollbar-hidden' since it isn't a known property of 'div'.

Did I miss something?

**Comment by bfwg** [comment] 2018-07-14 23:36
Hi @MortezaT , 2.0.0 uses `drag-scroll` as the carousel host element instead of div. 
```
  <drag-scroll style="width: 100px; height: 10px">
    Big text goes here...
  </drag-scroll>
```
More information can be found in the README.md.

Cheers.

**Comment by MortezaT** [comment] 2018-07-15 11:31
Hi @bfwg Thanks.
Is there any documentation for the new version, because It looks like they're way too different.
I can't understand why there is `20px` addition to the width and height of `.drag-scroll-content`.

**Comment by bfwg** [comment] 2018-07-16 00:55
To hide the scroll bar, we need to create a new wrapper div and insert the div between the parent div and the carousel div(.drag-scroll-content).

For example:
This is a normal carousel
![image](https://user-images.githubusercontent.com/12819525/30182916-5afda62a-93cd-11e7-95ae-265ee1eb0368.png)

When we try to hide the scrollbar, there is no magic! We simply create a wrapper div, and set the size of that wrapper div as the same as container div but minus its scrollbar width/height. The `20px` is the height/weight of the scrollbar in the current browser. 

![image](https://user-images.githubusercontent.com/12819525/30183140-2909d1b0-93ce-11e7-98f6-3a60ad1e6812.png)


Finally, we detach the container div, attach the wrapper div to parent div and insert the container div back to the wrapper div.
![image](https://user-images.githubusercontent.com/12819525/30183187-5ef4d5ea-93ce-11e7-
87b2-0e82505d2972.png)


Since the wrapper's overflow attribute has been set to 'hidden', the scrollbars are no longer shown.
I hope my drawing skill is still up to the game 😛 

Let me know if you have more questions, or if the new version is causing you any issues. 

Thanks!

**Comment by MortezaT** [comment] 2018-07-18 08:39
@bfwg 
Thanks. Now with this visual explanation everything is obvious for me and I confess this is a smart idea.
Everything looks fine except the very first time navigation. I have to drag a little bit before ( just a bit not a complete photo) to get `navs` working.
Method `moveRight` works at the moment and moves scroll to the left (end)

**Comment by bfwg** [comment] 2018-10-25 16:55
I am going to close this issue. Please let me know if I need to reopen this. Thanks!

**Closed by bfwg** 2018-10-25 16:55 UTC

**Comment by nicholasirsyad** [comment] 2024-04-13 05:06
Dear @bfwg 

In my case, when the webapp is opened in different sized windows sometimes the reachesRightBound or the moveRight() method does not work. Sometimes reachesRightBound does not return true when the carousel's already showing the last item.

It depends on the width of the windows too. When I dragged the window, my carousel adjust the width because I set it to width: 100%. But at certain widths, it seems the carousel is stuck - there seems to be an extra padding at the right that moveRight() wouldn't scroll. So the value for reachesRightBound always return false, even though it's already at the right most item.
