### ISSUE TITLE
drag-scroll-disabled alternative for children

### ISSUE THREAD

**Issue by CrackerakiUA** [bfwg/ngx-drag-scroll#144] opened 2018-06-12 21:34 UTC
* **I'm submitting a feature request**

It would be nice to have something like `drag-scroll-disabled` attribute which will disable drag scroll on that element and all children elements of that. At the moment I am fighting to make `drag-scroll-disabled="BOOL"` or `drag-scroll-disabled="{{BOOL}}"` and `mouseenter, mouseleave` without success.

**Comment by bfwg** [comment] 2018-06-12 21:57
Hi, @CrackerakiUA . Have you tried`[drag-scroll-disabled]="disabled"`?

**Comment by CrackerakiUA** [comment] 2018-06-13 15:36
adding below code
```
 dragScroll drag-scroll-y-disabled='true' snap-disabled='true' [drag-scroll-disabled]="bool"
```
and on child place:
```
 (mouseenter)="bool" (mouseleave)="bool"
```
also presenting bool to see if it's changing. `[drag-scroll-disabled]` feels like it working on start value and when I change the variable, it don't change. Strange because in your example toggle is working.

**Comment by bfwg** [comment] 2018-06-13 17:23
Correct me if I'm wrong. Basically, you want `drag-scroll-disabled` to disable `mouseenter`, and `mouseleave` for all children element in the directive container.

**Comment by CrackerakiUA** [comment] 2018-06-13 19:53
it's not like for all children elements, cool feature would be to add an attribute to any child and for that child drag scroll would be canceled (in a way stopPropagation works).

**Comment by CrackerakiUA** [comment] 2018-06-13 20:05
Theoretically if I implement your demo it should work nice, but in my case, I have tons of elements in that container and disable is not working well.

**Comment by bfwg** [comment] 2018-06-13 21:38
Do you have a code snippet to share? Or can you fork the demo app and show me what do you mean exactly? I'm having a hard time to picture the use case with reading the code or demo.

**Comment by CrackerakiUA** [comment] 2018-06-14 02:49
```
<div class="container" dragScroll drag-scroll-y-disabled="true" snap-disabled="true">
	<header title="This should drag background">Something is here</header>
	<div drag-scroll-disable>Content</div>
	<div drag-scroll-disable>Content</div>
	<div drag-scroll-disable>Content</div>
	<div drag-scroll-disable>Content</div>
	<div drag-scroll-disable>Content</div>
	<footer title="This should drag background">Something else</footer>
	<!-- everything else should also drag background -->
</div>
```
Please check the code, if that will not clarify the idea, I will make a demo.

**Comment by bfwg** [comment] 2018-06-16 08:50
Thanks @CrackerakiUA , I got the idea. I will soon push version 2.0.0 out which will introduce a `drag-scroll-item` to mark all children elements. Once 2.0.0 is out, I can add this feature right after.

**Comment by CrackerakiUA** [comment] 2018-06-16 12:39
Cool, do you know when that will be, do you need any help on that?

**Comment by bfwg** [comment] 2018-06-17 04:12
The PR for 2.0 is up https://github.com/bfwg/ngx-drag-scroll/pull/145. I'm just doing a bunch of tests to make sure there is no regression. Here is the new README https://github.com/bfwg/ngx-drag-scroll/blob/7592e3b08894ce23347c392c3fb88fc4c545323b/README.md

It'd be great if you can give that PR a run so that we can make it live faster. Thanks!

**Comment by CrackerakiUA** [comment] 2018-06-19 23:04
drag-scroll-item
looks so nice, it's possible also to use something like 
ignore-drag-scroll-item
imagine an example as trello where you have columns which is not dragging the background.

**Comment by bfwg** [comment] 2018-06-19 23:50
Yup, I'm thinking of adding a `drag-scroll-disabled" attribute in the `drag-scroll-item` to disable the parent app from dragging and scrolling. What do you think?

**Comment by CrackerakiUA** [comment] 2019-01-30 13:59
Hello, any progress on this?

**Comment by bfwg** [comment] 2019-01-30 21:07
It was on one of my working branches and I forgot about it. I'll push my changes and hopefully get it in by today.  Sorry about that 😅

**Comment by CrackerakiUA** [comment] 2019-01-31 06:34
Sounds nice, thank you

**Comment by bfwg** [comment] 2019-01-31 17:16
The change is in 7.1.0. You can add a ‘drag-disabled’ attribute on the child element, and it will disable dragging on that element.

**Comment by bfwg** [comment] 2019-01-31 17:17
Resolved in #205

**Closed by bfwg** 2019-01-31 17:16 UTC
Labels: feature request

**Comment by bfwg** [comment] 2019-02-02 22:16
You task element is missing the `drag-scroll-item` attribute.
```
 <drag-scroll [drag-scroll-y-disabled]="true">
	<task drag-scroll-item drag-disabled></task>
	<task drag-scroll-item drag-disabled></task>
	<task drag-scroll-item drag-disabled></task>
	<task drag-scroll-item drag-disabled></task>
	<task drag-scroll-item drag-disabled></task>
	<task drag-scroll-item drag-disabled></task>
</drag-scroll>
```

**Comment by CrackerakiUA** [comment] 2019-02-03 08:45
right after I adding  `drag-scroll-item` drag-scroll stopping to work. Tried the case you added and also:
```
 <drag-scroll [drag-scroll-y-disabled]="true" drag-scroll-item>
	<task drag-disabled></task>
	<task drag-disabled></task>
	<task drag-disabled></task>
	<task drag-disabled></task>
	<task drag-disabled></task>
	<task drag-disabled></task>
</drag-scroll>
```
and the next scenario:
```
<drag-scroll [drag-scroll-y-disabled]="true">
 	<ng-container drag-scroll-item>
		<task drag-disabled></task>
		<task drag-disabled></task>
		<task drag-disabled></task>
		<task drag-disabled></task>
		<task drag-disabled></task>
		<task drag-disabled></task>
 	</ng-container>
</drag-scroll>
```

**Comment by bfwg** [comment] 2019-02-04 00:38
That is strange. Can you reproduce in the demo app because it is working fine for me.

**Comment by CrackerakiUA** [comment] 2019-02-04 08:44
I used your example and made something like below which is not working:
```
<drag-scroll class="demo-one"
  drag-scroll-y-disabled="true"
  scrollbar-hidden="true"
  (dsInitialized)="onDragScrollInitialized()"
  (indexChanged)="onIndexChanged($event)"
  (reachesLeftBound)="leftBoundStat($event)"
  (reachesRightBound)="rightBoundStat($event)"
  (snapAnimationFinished)="onSnapAnimationFinished()"
  #nav
  >
  <ng-container *ngFor="let image of imagelist; let i = index;" drag-scroll-item>
    <img *ngIf="i%2==0" [src]="'assets/img/' + image" (click)="clickItem(image)" title="{{i}}" drag-disabled/>
    <img *ngIf="i%2!=0" [src]="'assets/img/' + image" (click)="clickItem(image)" title="{{i}}"/>
  </ng-container>

</drag-scroll>
```

**Comment by CrackerakiUA** [comment] 2019-02-06 12:28
@bfwg is my example working on your side?

**Comment by arman2r** [comment] 2020-03-03 16:34
@bfwg  With what or why? when using drag-scroll blocks all the elements of ghost drag image on the website, I can't find how to solve this

**Comment by bfwg** [comment] 2020-03-03 17:53
This issue is a dup, please see my comments https://github.com/bfwg/ngx-drag-scroll/issues/223#issuecomment-494259349 

I've pointed out the issue. @arman2r

**Comment by brons-git** [comment] 2022-02-01 20:51
`(mousedown)="$event.stopPropagation()"` added to the child should do the trick

**Comment by CrackerakiUA** [comment] 2022-02-01 21:38
in case of child dragging object it will not work

**Comment by brons-git** [comment] 2022-02-01 21:41
I'm using it on a child with cdkDrag and it works. I'm able to drag the child around with the background staying in place.

**Comment by CrackerakiUA** [comment] 2022-02-01 21:43
ok, sounds interesting, I will test it, thank you

**Comment by CrackerakiUA** [comment] 2022-02-02 19:01
not working with ng2-dragula, but good tip :)
