### ISSUE TITLE
Add stopScrolling() function

### ISSUE THREAD

**Issue by ventr1x** [bfwg/ngx-drag-scroll#148] opened 2018-06-26 08:53 UTC
Feature request:

Currently this directive has issues with other directives that use any kind of drag/drop events.
For example using a drag&drop plugin the panning starts on dropping an element and only stops after clicking the mouse.
A very simple "stopScrolling()" function would help there, as it's understandably nearly impossible to support other directives.
But with more useful exposed functions people could simply call stopScrolling() on their dop event to immediately stop the panning when necessary.

Currently I'm using onMouseUp(null); to get around that issue, but that is not very useful as it might break in the future (whenever the event object is used it would throw an exception).

**Comment by bfwg** [comment] 2018-06-28 00:13
@ventr1x  is this a duplicate of https://github.com/bfwg/ngx-drag-scroll/issues/144?

**Closed** 2018-07-11 17:01 UTC
