### ISSUE TITLE
Active item 

### ISSUE THREAD

**Issue by MaciejWWojcik** [bfwg/ngx-drag-scroll#163] opened 2018-08-08 14:49 UTC
I'm submitting 
  - [*] feature request

I want to ask if there is any possibility to get an item which is 'active'? I mean is there any method to check what item is on the center. 

* **What is the motivation / use case for changing the behavior?**
The use case is like this: 
I have plenty of items which are for example avatars, the user can swipe from left to right to choose avatar it wants. When the user clicks 'save' it wants to save the active avatar - the one on the center.

**Comment by bfwg** [comment] 2018-08-13 17:08
I believe this is a duplicate of #132

**Closed** 2018-08-29 18:13 UTC
Labels: feature request
